export const GET_CITIES = 'GET_CITIES';
export const REQUEST_CITIES = 'REQUEST_CITIES';

export const GET_ITINERARIES = 'GET_ITINERARIES';
export const REQUEST_ITINERARIES = 'REQUEST_ITINERARIES';

export const GET_ACT = 'GET_ACT';
export const REQUEST_ACT = 'REQUEST_ACT';

export const WILL_REGISTER_USER = 'WILL_POST_USER';
export const SUCCESS_REGISTER_USER = 'POST_USER';
export const FAIL_REGISTER_USER = 'POST_USER';

export const WILL_LOGIN_USER = 'WILL_LOGIN_USER';
export const SUCCESS_LOGIN_USER = 'SUCCESS_LOGIN_USER';
export const FAIL_LOGIN_USER = 'FAIL_LOGIN_USER';

export const AUTH_USER = 'AUTH_USER';
